// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5ogPX4FRa9VCjhR0JmGTjazOWD41qBYM',
    appId: '1:858867295458:web:9c466e305b0e831620eabb',
    messagingSenderId: '858867295458',
    projectId: 'temperature-96805',
    authDomain: 'temperature-96805.firebaseapp.com',
    databaseURL: 'https://temperature-96805-default-rtdb.firebaseio.com',
    storageBucket: 'temperature-96805.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMBMSI3hPpcl8bMDZaQDXQxcO6Kx08f0M',
    appId: '1:858867295458:android:7cb52b537cd2ed3720eabb',
    messagingSenderId: '858867295458',
    projectId: 'temperature-96805',
    databaseURL: 'https://temperature-96805-default-rtdb.firebaseio.com',
    storageBucket: 'temperature-96805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCph7CKGRyMoB9iJ2gY3fRCwSOZzK4MrVc',
    appId: '1:858867295458:ios:894646ce31189c6220eabb',
    messagingSenderId: '858867295458',
    projectId: 'temperature-96805',
    databaseURL: 'https://temperature-96805-default-rtdb.firebaseio.com',
    storageBucket: 'temperature-96805.appspot.com',
    iosBundleId: 'com.example.appTemperature',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCph7CKGRyMoB9iJ2gY3fRCwSOZzK4MrVc',
    appId: '1:858867295458:ios:894646ce31189c6220eabb',
    messagingSenderId: '858867295458',
    projectId: 'temperature-96805',
    databaseURL: 'https://temperature-96805-default-rtdb.firebaseio.com',
    storageBucket: 'temperature-96805.appspot.com',
    iosBundleId: 'com.example.appTemperature',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5ogPX4FRa9VCjhR0JmGTjazOWD41qBYM',
    appId: '1:858867295458:web:2d89bd57aa7736b720eabb',
    messagingSenderId: '858867295458',
    projectId: 'temperature-96805',
    authDomain: 'temperature-96805.firebaseapp.com',
    databaseURL: 'https://temperature-96805-default-rtdb.firebaseio.com',
    storageBucket: 'temperature-96805.appspot.com',
  );
}
