// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcOZJJ7BILHm0JghiHrkKaDzYs0XsvzfI',
    appId: '1:687785053806:web:7c3c88a0fa6e9e738ba07f',
    messagingSenderId: '687785053806',
    projectId: 'temperature-31bfa',
    authDomain: 'temperature-31bfa.firebaseapp.com',
    databaseURL: 'https://temperature-31bfa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'temperature-31bfa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmL3Dj9F1VvAS1XdGEBBcpms1eCeMIT0Y',
    appId: '1:687785053806:android:b22cafea4e19e1a88ba07f',
    messagingSenderId: '687785053806',
    projectId: 'temperature-31bfa',
    databaseURL: 'https://temperature-31bfa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'temperature-31bfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY3Gg01BxPGzhRVpmHS8G7XfbF8kp0F2w',
    appId: '1:687785053806:ios:9f0f59e49389ca1e8ba07f',
    messagingSenderId: '687785053806',
    projectId: 'temperature-31bfa',
    databaseURL: 'https://temperature-31bfa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'temperature-31bfa.appspot.com',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY3Gg01BxPGzhRVpmHS8G7XfbF8kp0F2w',
    appId: '1:687785053806:ios:9f0f59e49389ca1e8ba07f',
    messagingSenderId: '687785053806',
    projectId: 'temperature-31bfa',
    databaseURL: 'https://temperature-31bfa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'temperature-31bfa.appspot.com',
    iosBundleId: 'com.example.appFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcOZJJ7BILHm0JghiHrkKaDzYs0XsvzfI',
    appId: '1:687785053806:web:4294addb718420698ba07f',
    messagingSenderId: '687785053806',
    projectId: 'temperature-31bfa',
    authDomain: 'temperature-31bfa.firebaseapp.com',
    databaseURL: 'https://temperature-31bfa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'temperature-31bfa.appspot.com',
  );
}
